# Generated by Django 4.2.3 on 2023-08-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_categoria_reserva_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='base.categoria'),
        ),
    ]
